// import './globals.css'
import 'bootstrap/dist/css/bootstrap.css';
import { Inter } from 'next/font/google'
import "bootstrap-icons/font/bootstrap-icons.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>{children}</body>
    </html>
  )
}
